# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - npm add -D vitepress@next
  build:
    - npx vitepress build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r .vitepress/dist/* $READTHEDOCS_OUTPUT/html/