# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the 
build:
  os: ubuntu-24.04
  tools:
    nodejs: "latest"
  jobs:
         install:
             - npm ci
         build:
             html:
                 # The site was created by running `vitepress init`
                 # and following the official guide
                 # https://vitepress.dev/guide/getting-started
                 - npx vitepress build
                 - mkdir -p $READTHEDOCS_OUTPUT/html
                 - cp -r .vitepress/dist/* $READTHEDOCS_OUTPUT/html
                 